"""Reading setup/catalog.json - what to install and where it goes.

The catalogue is generated by tools/make_catalog.py from a working machine, so
everything here is a lookup rather than a decision.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from app.paths import resource_dir

HERE = Path(__file__).resolve().parent
#: Ships with the program, so it is read from the bundle when built.
CATALOG_PATH = resource_dir() / "setup" / "catalog.json"

#: Hosts that can take an account token. Sending one to a file that does not
#: need it is harmless, so this decides only whether the header goes out - it
#: does not mean the file is gated. Gating is recorded per model, from an
#: actual 401, because most files on these hosts are open.
TOKEN_HOSTS = {"huggingface.co": "HuggingFace", "civitai.com": "Civitai"}


def host_of(url: str) -> str:
    return url.split("/")[2].lower() if "//" in url else ""


def token_host_for(url: str) -> str:
    """Which account's token belongs on a request to this exact URL.

    Always decide from the URL being fetched, never from the model it belongs
    to. A mirrored model still records its HuggingFace origin, and sending the
    user's HuggingFace token to the mirror's host would hand their credential
    to a server that has no business seeing it.
    """
    return TOKEN_HOSTS.get(host_of(url), "")


@dataclass
class Model:
    name: str                       # as the workflow writes it, e.g. "Flux 2\\x.gguf"
    folder: str                     # models subfolder: unet, vae, clip …
    url: str | None
    bytes: int = 0
    gated: bool = False             # confirmed to need an account, not guessed
    mirror: str | None = None       # our own copy, for files behind a sign-in
    sha256: str = ""                # recorded for mirrored files, see sources()

    @property
    def filename(self) -> str:
        return Path(self.name).name

    @property
    def relative_path(self) -> Path:
        """Where it lands under models/, keeping any subfolder the name carries."""
        return Path(self.folder) / self.name

    @property
    def installable(self) -> bool:
        return bool(self.url or self.mirror)

    @property
    def sources(self) -> list[tuple[str, str]]:
        """Where to try, best first, as (label, url) pairs.

        The mirror comes first because it needs no account - that is the whole
        reason it exists. The original stays as the fallback, so a revoked
        share link or a server outage degrades to "you need a key" rather than
        to a failed install.
        """
        out = []
        if self.mirror:
            out.append(("mirror", self.mirror))
        if self.url:
            out.append(("original", self.url))
        return out

    @property
    def host(self) -> str:
        return host_of(self.url or "")

    @property
    def token_host(self) -> str:
        """Which account's token the original source would want."""
        return token_host_for(self.url or "")


@dataclass
class NodePack:
    name: str
    source: str                     # "git" | "cnr" | "unknown"
    url: str | None = None
    commit: str | None = None
    id: str | None = None
    version: str | None = None


@dataclass
class Group:
    key: str
    label: str
    models: list[str] = field(default_factory=list)
    nodes: list[str] = field(default_factory=list)
    workflows: list[str] = field(default_factory=list)
    bytes: int = 0


class Catalog:
    """Everything EasyAISetup can install."""

    def __init__(self, path: Path | str = CATALOG_PATH):
        self.path = Path(path)
        raw = json.loads(self.path.read_text(encoding="utf-8"))
        self.comfyui: dict = raw["comfyui"]
        self.models = {
            name: Model(name=name, folder=e.get("dir", "checkpoints"),
                        url=e.get("url"), bytes=e.get("bytes", 0),
                        gated=bool(e.get("gated")), mirror=e.get("mirror"),
                        sha256=e.get("sha256", ""))
            for name, e in raw["models"].items()
        }
        self.nodes = {
            name: NodePack(name=name, source=e.get("source", "unknown"),
                           url=e.get("url"), commit=e.get("commit"),
                           id=e.get("id"), version=e.get("version"))
            for name, e in raw["nodes"].items()
        }
        self.groups = {
            key: Group(key=key, label=g.get("label", key), models=g.get("models", []),
                       nodes=g.get("nodes", []), workflows=g.get("workflows", []),
                       bytes=g.get("bytes", 0))
            for key, g in raw["groups"].items()
        }

    # -- selections --------------------------------------------------------
    def models_for(self, groups) -> list[Model]:
        """Every model the chosen groups need, each listed once."""
        seen, out = set(), []
        for key in groups:
            for name in self.groups[key].models:
                if name not in seen:
                    seen.add(name)
                    out.append(self.models[name])
        return out

    def nodes_for(self, groups) -> list[NodePack]:
        seen, out = set(), []
        for key in groups:
            for name in self.groups[key].nodes:
                if name not in seen:
                    seen.add(name)
                    out.append(self.nodes[name])
        return out

    def download_bytes(self, groups, include_base: bool = True) -> int:
        """How much has to come down the wire for this selection."""
        total = sum(m.bytes for m in self.models_for(groups) if m.installable)
        if include_base:
            total += int(self.comfyui["portable"].get("bytes", 0))
        return total

    def blocked(self, groups) -> list[Model]:
        """Chosen models with no download URL - the user must supply these."""
        return [m for m in self.models_for(groups) if not m.installable]

    def gated(self, groups) -> list[Model]:
        """Chosen models that will actually ask the user for an account key.

        A gated model we mirror ourselves does not, which is the entire point
        of the mirror - so it must not be counted here, or the window would go
        on warning about keys nobody needs.
        """
        return [m for m in self.models_for(groups)
                if m.installable and m.gated and not m.mirror]

    def mirrored(self, groups) -> list[Model]:
        """Chosen models served from our own copy rather than their origin."""
        return [m for m in self.models_for(groups) if m.mirror]


def human_bytes(n: float) -> str:
    for unit, size in (("TB", 1024 ** 4), ("GB", 1024 ** 3), ("MB", 1024 ** 2), ("KB", 1024)):
        if n >= size:
            return f"{n / size:.1f} {unit}"
    return f"{int(n)} B"
