"""Reading setup/catalog.json - what to install and where it goes.

The catalogue is generated by tools/make_catalog.py from a working machine, so
everything here is a lookup rather than a decision.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from app.paths import resource_dir

HERE = Path(__file__).resolve().parent
#: Ships with the program, so it is read from the bundle when built.
CATALOG_PATH = resource_dir() / "setup" / "catalog.json"

#: Hosts that can take an account token. Sending one to a file that does not
#: need it is harmless, so this decides only whether the header goes out - it
#: does not mean the file is gated. Gating is recorded per model, from an
#: actual 401, because most files on these hosts are open.
TOKEN_HOSTS = {"huggingface.co": "HuggingFace", "civitai.com": "Civitai"}


def host_of(url: str) -> str:
    return url.split("/")[2].lower() if "//" in url else ""


def token_host_for(url: str) -> str:
    """Which account's token belongs on a request to this exact URL.

    Always decide from the URL being fetched, never from the model it belongs
    to. A mirrored model still records its HuggingFace origin, and sending the
    user's HuggingFace token to the mirror's host would hand their credential
    to a server that has no business seeing it.
    """
    return TOKEN_HOSTS.get(host_of(url), "")


@dataclass
class Model:
    name: str                       # as the workflow writes it, e.g. "Flux 2\\x.gguf"
    folder: str                     # models subfolder: unet, vae, clip …
    url: str | None
    bytes: int = 0
    gated: bool = False             # confirmed to need an account, not guessed
    mirror: str | None = None       # our own copy, for files behind a sign-in
    sha256: str = ""                # recorded for mirrored files, see sources()
    #: A folder of its own, from setup-settings.json. Empty means the models
    #: folder's own subfolder for this kind ("unet", "loras"...).
    to: str = ""

    @property
    def filename(self) -> str:
        return Path(self.name).name

    @property
    def relative_path(self) -> Path:
        """Where it lands under models/, keeping any subfolder the name carries."""
        return Path(self.folder) / self.name

    @property
    def installable(self) -> bool:
        return bool(self.url or self.mirror)

    @property
    def sources(self) -> list[tuple[str, str]]:
        """Where to try, best first, as (label, url) pairs.

        The mirror comes first because it needs no account - that is the whole
        reason it exists. The original stays as the fallback, so a revoked
        share link or a server outage degrades to "you need a key" rather than
        to a failed install.
        """
        out = []
        if self.mirror:
            out.append(("mirror", self.mirror))
        if self.url:
            out.append(("original", self.url))
        return out

    @property
    def host(self) -> str:
        return host_of(self.url or "")

    @property
    def token_host(self) -> str:
        """Which account's token the original source would want."""
        return token_host_for(self.url or "")


@dataclass
class NodePack:
    name: str
    source: str                     # "git" | "cnr" | "unknown"
    url: str | None = None
    commit: str | None = None
    id: str | None = None
    version: str | None = None


@dataclass
class WorkflowItem:
    """One workflow to install, from where to where.

    ``source`` is "built-in" (shipped inside EasyAI Setup), a file path, or a
    web link. ``to`` is a folder under the workflows folder - normally the
    group's own, such as "image" - or a full path.
    """
    file: str
    source: str = "built-in"
    to: str = ""


@dataclass
class Group:
    key: str
    label: str
    models: list[str] = field(default_factory=list)
    nodes: list[str] = field(default_factory=list)
    workflows: list[str] = field(default_factory=list)
    bytes: int = 0
    workflow_items: list[WorkflowItem] = field(default_factory=list)


#: Where things go when nothing says otherwise: models into the ComfyUI being
#: installed, workflows into a folder beside it that EasyAI is pointed at.
DEFAULT_FOLDERS = {"models": "", "workflows": "EasyAI-workflows"}


class Catalog:
    """Everything EasyAISetup can install."""

    def __init__(self, path: Path | str = CATALOG_PATH, raw: dict | None = None,
                 list_path: Path | None = None):
        self.path = Path(path)
        if raw is None:
            raw = json.loads(self.path.read_text(encoding="utf-8"))
        #: The editable setup-settings.json this came from, if any. Workflow
        #: sources given as relative paths are read from beside it.
        self.list_path = Path(list_path) if list_path else None
        self.folders = {**DEFAULT_FOLDERS, **(raw.get("folders") or {})}
        self.comfyui: dict = raw["comfyui"]
        self.models = {
            name: Model(name=name, folder=e.get("dir", "checkpoints"),
                        url=e.get("url"), bytes=e.get("bytes", 0),
                        gated=bool(e.get("gated")), mirror=e.get("mirror"),
                        sha256=e.get("sha256", ""), to=str(e.get("to") or ""))
            for name, e in raw["models"].items()
        }
        self.nodes = {
            name: NodePack(name=name, source=e.get("source", "unknown"),
                           url=e.get("url"), commit=e.get("commit"),
                           id=e.get("id"), version=e.get("version"))
            for name, e in raw["nodes"].items()
        }
        self.groups = {
            key: Group(key=key, label=g.get("label", key), models=g.get("models", []),
                       nodes=g.get("nodes", []), workflows=g.get("workflows", []),
                       bytes=g.get("bytes", 0),
                       workflow_items=[
                           WorkflowItem(file=str(w.get("file", "")),
                                        source=str(w.get("from") or "built-in"),
                                        to=str(w.get("to") or ""))
                           for w in g.get("workflow_items") or []]
                       or [WorkflowItem(file=f) for f in g.get("workflows", [])])
            for key, g in raw["groups"].items()
        }

    # -- where things go -----------------------------------------------------
    def models_root(self, comfy_models: Path, target: Path) -> Path:
        """The folder models go under: ComfyUI's own unless the list says."""
        return _resolve(self.folders.get("models") or "", Path(target), Path(comfy_models))

    def model_destination(self, model: Model, comfy_models: Path, target: Path) -> Path:
        """The exact file a model is written to.

        A model's folder is either one under the models folder ("unet") or a
        full path of its own; the subfolder in its name is kept either way,
        because that is what the workflow asks ComfyUI for.
        """
        return self.model_folder(model, comfy_models, target) / Path(model.name.replace("\\", "/"))

    def model_folder(self, model: Model, comfy_models: Path, target: Path) -> Path:
        """The folder a model's name is resolved in - what ComfyUI must search."""
        default = self.models_root(comfy_models, target) / model.folder
        return _resolve(model.to, Path(target), default)

    def workflows_root(self, target: Path) -> Path:
        return _resolve(self.folders.get("workflows") or DEFAULT_FOLDERS["workflows"],
                        Path(target), Path(target) / DEFAULT_FOLDERS["workflows"])

    # -- selections --------------------------------------------------------
    def models_for(self, groups) -> list[Model]:
        """Every model the chosen groups need, each listed once."""
        seen, out = set(), []
        for key in groups:
            for name in self.groups[key].models:
                if name not in seen:
                    seen.add(name)
                    out.append(self.models[name])
        return out

    def nodes_for(self, groups) -> list[NodePack]:
        seen, out = set(), []
        for key in groups:
            for name in self.groups[key].nodes:
                if name not in seen:
                    seen.add(name)
                    out.append(self.nodes[name])
        return out

    def download_bytes(self, groups, include_base: bool = True) -> int:
        """How much has to come down the wire for this selection."""
        total = sum(m.bytes for m in self.models_for(groups) if m.installable)
        if include_base:
            total += int(self.comfyui["portable"].get("bytes", 0))
        return total

    def blocked(self, groups) -> list[Model]:
        """Chosen models with no download URL - the user must supply these."""
        return [m for m in self.models_for(groups) if not m.installable]

    def gated(self, groups) -> list[Model]:
        """Chosen models that will actually ask the user for an account key.

        A gated model we mirror ourselves does not, which is the entire point
        of the mirror - so it must not be counted here, or the window would go
        on warning about keys nobody needs.
        """
        return [m for m in self.models_for(groups)
                if m.installable and m.gated and not m.mirror]

    def mirrored(self, groups) -> list[Model]:
        """Chosen models served from our own copy rather than their origin."""
        return [m for m in self.models_for(groups) if m.mirror]


def _resolve(value: str, target: Path, default: Path) -> Path:
    """A folder setting: empty means the default, relative means inside the
    install folder, and a full path is used exactly as written."""
    value = (value or "").strip()
    if not value:
        return default
    path = Path(value)
    return path if path.is_absolute() else target / path


def human_bytes(n: float) -> str:
    for unit, size in (("TB", 1024 ** 4), ("GB", 1024 ** 3), ("MB", 1024 ** 2), ("KB", 1024)):
        if n >= size:
            return f"{n / size:.1f} {unit}"
    return f"{int(n)} B"
